import type { PdfData } from './pdfTypes';

export function buildSamplePdfData(): PdfData {
  return {
    budgetNumber: '2026-001',
    budgetDate: new Date().toISOString(),
    type: 'Obra Nova',
    clientName: 'Joan Garcia',
    clientAddress: 'C/ del Mar, 24',
    clientTown: 'Calella',
    clientPhone: '600 123 456',
    clientEmail: 'joan@example.com',
    poolLength: 5,
    poolWidth: 4,
    poolDepthMin: 1.2,
    poolDepthMax: 1.6,
    poolVolumeM3: 28,
    hasInteriorStairs: true,
    interiorStairsType: 'plataforma',
    poolType: 'particular',
    poolShape: 'regular',
    hasExteriorStairs: true,
    extStairsLength: 3,
    extStairsWidth: 1.2,
    waterproofingSystem: 'impertot',
    stairsDimensions: '1,20 x 1,50 x 1,20',
    hasPlatform: true,
    platformDimensions: '2,80 x 1,50 x 0,80',
    depuracioCapacityM3: 28,
    filtreInclosTipus: 'sorra',
    filtreInclosName: 'ASTRAL ASTER/ICE 600 SORRA SILICE + VÀLVULA 6V',
    afmEnabled: false,
    afmQty: 12,
    afmExtraSale: 395.28,
    prefiltreEnabled: false,
    prefiltreName: 'HYDROSPIN COMPACT',
    prefiltreSale: 447,
    accSkimmersQty: 2,
    accSkimmersTotal: 242,
    accImpulsorsQty: 4,
    accImpulsorsTotal: 56,
    accEmbornalQty: 1,
    accEmbornalTotal: 42,
    accNetejafonsQty: 1,
    accNetejafonsTotal: 15,
    accReguladorQty: 1,
    accReguladorTotal: 294,
    accFocusLedQty: 2,
    accFocusLedTotal: 735,
    accFocusLedDescription: 'Focus LED blancs Lumiplus Flexiniche Ref. 76576',
    quadreTotal: 548,
    presaTerraTotal: 305,
    fontaneriaTotal: 1612,
    escomesaIncluded: true,
    phaseStructuralTotal: 9980,
    vasTotal: 8450,
    elementsEstructuralsTotal: 1530,
    phaseAcabatsTotal: 7892,
    coronamentActuacioLabel: 'Subministrament i col·locació',
    coronamentMl: 32.4,
    coronamentBeuradaLabel: 'Beurada cimentosa',
    coronamentBeuradaColor: '',
    coronamentTipusLabel: 'GRES PORCELÀNIC 31×62',
    coronamentTipusFormat: 'ROSAGRES L62',
    coronamentModelName: undefined,
    coronamentModelImageUrl: undefined,
    coronamentTotal: 4250,
    revestimentTotal: 3642,
    revestimentActuacioLabel: 'Subministrament i col·locació',
    revestimentSurfaceText: 'de mosaic vitri en tota la superfície interior de la piscina',
    revestimentTipusLabel: 'GRESSITE',
    revestimentTipusFormat: '2,5 × 2,5 cm',
    revestimentBeuradaLabel: 'Beurada epoxi',
    revestimentBeuradaColor: 'Blanc',
    revestimentModelName: undefined,
    revestimentModelImageUrl: undefined,
    phaseDepuracioTotal: 7811,
    phaseElectricitatTotal: 987,
    totalSale: 26670,
    // Page 8 — Accessoris
    accBasicsColor: 'blanc',
    accBasicLines: [
      { label: 'BOQUILLA IMPULSIÓN MULTIFLOW (HORMIGON)', qty: 4, total: 56 },
      { label: 'SKIMMER BOCA STANDARD TAPA CIRCULAR ASTRAL', qty: 2, total: 242 },
      { label: 'SUMIDERO 210mm STANDARD (HORMIGON)', qty: 1, total: 42 },
      { label: '76576 - FLEXINICHE: EMBELLIDOR BLANC + PUNT DE LLUM BLANC AC + NÍNXOL + PASSACABLES - FORMIGÓ', qty: 2, total: 735 },
      { label: 'REGULADOR DE NIVEL ASTRAL + REGULADOR DE PRESIÓN', qty: 1, total: 294 },
      { label: 'BOQUILLA ASPIRACIÓN D50 PN10 ENCOLAR (HORMIGON)', qty: 1, total: 15 },
    ],
    accBasicTotal: 1384,
    accOptionalLines: [
      { label: 'Escala inox AISI-316 4 graons', qty: 1, total: 380 },
      { label: 'Plat de dutxa', qty: 1, total: 550 },
    ],
    accOptionalTotal: 930,
    instalacionsTotal: 4926,
    // Annex sample — Projecte Tècnic d'Obra included
    annexProjecteEstat: 'inclos',
    annexProjecteName: "PROJECTE D'OBRA",
    annexProjecteAmount: 1300,
    phaseAnnexTotal: 1300,
  };
}
