/**
 * Maps a budgets row (snake_case from Supabase) to the BudgetDraft shape
 * (camelCase) used by the wizard, the PDF generator and the formula engine.
 *
 * Extracted so multiple flows (edit wizard, technical sheet, etc.) can
 * reuse the same mapping without duplicating ~200 lines of field assignments.
 */
import { supabase } from '@/integrations/supabase/client';
import type { BudgetDraft, BudgetPhase } from '@/stores/budgetStore';

export interface LoadedBudget {
  draft: BudgetDraft;
  raw: any;
}

export async function loadBudgetAsDraft(budgetId: string): Promise<LoadedBudget> {
  const { data, error } = await supabase.from('budgets').select('*').eq('id', budgetId).single();
  if (error || !data) throw new Error('Pressupost no trobat');

  // Persisted phases (only manual items survive here; formula items are
  // recomputed on-the-fly by the formula engine).
  const { data: dbPhases } = await supabase
    .from('budget_phases')
    .select('*, budget_items(*)')
    .eq('budget_id', budgetId)
    .order('order');

  // Cobertor display names
  let cobertorModelName: string | undefined;
  let cobertorColorName: string | undefined;
  if ((data as any).annex_cobertor_model_id) {
    const { data: m } = await supabase.from('cover_models').select('name').eq('id', (data as any).annex_cobertor_model_id).maybeSingle();
    cobertorModelName = m?.name || undefined;
  }
  if ((data as any).annex_cobertor_color_id) {
    const { data: c } = await supabase.from('cover_colors').select('name').eq('id', (data as any).annex_cobertor_color_id).maybeSingle();
    cobertorColorName = c?.name || undefined;
  }

  const phases: BudgetPhase[] = (dbPhases || []).map((p: any) => ({
    id: p.id,
    name: p.name,
    order: p.order,
    items: (p.budget_items || [])
      .sort((a: any, b: any) => (a.order ?? 0) - (b.order ?? 0))
      .map((it: any) => ({
        id: it.id,
        description: it.description || '',
        unit: it.unit || 'ud',
        quantity: Number(it.quantity ?? 1),
        unitCost: (it.unit_cost ?? 0) / 100,
        unitSale: (it.unit_sale ?? 0) / 100,
        source: (it.source === 'formula' || it.source === 'wizard' || it.source === 'manual' ? it.source : 'manual') as any,
        wizardKey: it.wizard_key || undefined,
        subPhase: it.sub_phase ?? null,
        userEdited: it.user_edited === true,
      })),
  }));

  const draft: BudgetDraft = {
    id: data.id, type: data.type as any, clientName: data.client_name, clientNif: data.client_nif,
    clientAddress: data.client_address, clientTown: data.client_town, clientPhone: data.client_phone,
    clientEmail: data.client_email, budgetDate: data.budget_date, budgetNumber: data.number,
    internalNotes: data.internal_notes, poolType: data.pool_type as any, poolShape: data.pool_shape as any,
    poolLength: Number(data.pool_length), poolWidth: Number(data.pool_width),
    poolDepthMin: Number(data.pool_depth_min), poolDepthMax: Number(data.pool_depth_max),
    poolDepthAvg: (data as any).pool_depth_avg ? Number((data as any).pool_depth_avg) : undefined,
    hasElectrolisi: (data as any).has_electrolisi ?? undefined,
    kitMangueraSize: ((data as any).kit_manguera_size as any) || undefined,
    kitPertigaSize: ((data as any).kit_pertiga_size as any) || undefined,
    hasExteriorStairs: data.has_exterior_stairs, extStairsLength: Number(data.ext_stairs_length),
    extStairsWidth: Number(data.ext_stairs_width), interiorStairsType: data.interior_stairs_type as any,
    poolDisposition: ((data as any).pool_disposition as any) || 'enterrada',
    alturaVista: Number((data as any).altura_vista) || undefined,
    hasRebaix: !!(data as any).has_rebaix,
    rebaixAmount: Number((data as any).rebaix_amount) || undefined,
    hasAccessStair: !!(data as any).has_access_stair,
    accessStairWidth: Number((data as any).access_stair_width) || undefined,
    accessTotalLength: (() => {
      const sL = Number((data as any).access_stair_length) || 0;
      const pL = Number((data as any).access_platform_length) || 0;
      const t = sL + pL;
      return t > 0 ? Math.round(t * 100) / 100 : undefined;
    })(),
    stairsWidth: Number(data.stairs_width), stairsLength: Number(data.stairs_length),
    stairsHeight: Number(data.stairs_height), platformWidth: Number(data.platform_width),
    platformLength: Number(data.platform_length), platformHeight: Number(data.platform_height),
    benchWidth: Number(data.bench_width), benchLength: Number(data.bench_length),
    benchHeight: Number(data.bench_height),
    hasJacuzzi: (data as any).has_jacuzzi ?? undefined,
    jacuzziType: ((data as any).jacuzzi_type as any) || undefined,
    jacuzziPosition: ((data as any).jacuzzi_position as any) || undefined,
    jacuzziLength: (data as any).jacuzzi_length != null ? Number((data as any).jacuzzi_length) : undefined,
    jacuzziWidth: (data as any).jacuzzi_width != null ? Number((data as any).jacuzzi_width) : undefined,
    jacuzziDepth: (data as any).jacuzzi_depth != null ? Number((data as any).jacuzzi_depth) : undefined,
    jacuzziBenchCount: (data as any).jacuzzi_bench_count ?? undefined,
    jacuzziBenchDepth: (data as any).jacuzzi_bench_depth != null ? Number((data as any).jacuzzi_bench_depth) : undefined,
    jacuzziBenchHeight: (data as any).jacuzzi_bench_height != null ? Number((data as any).jacuzzi_bench_height) : undefined,
    jacuzziStairsCount: (data as any).jacuzzi_stairs_count ?? undefined,
    jacuzziStairsTread: (data as any).jacuzzi_stairs_tread != null ? Number((data as any).jacuzzi_stairs_tread) : undefined,
    jacuzziAirJetsCount: (data as any).jacuzzi_air_jets_count ?? undefined,
    jacuzziAirJetsIntakeCount: (data as any).jacuzzi_air_jets_intake_count ?? undefined,
    jacuzziAirPumpQty: (data as any).jacuzzi_air_pump_qty ?? undefined,
    jacuzziAirPumpArticleId: (data as any).jacuzzi_air_pump_article_id || undefined,
    jacuzziWaterJetsCount: (data as any).jacuzzi_water_jets_count ?? undefined,
    jacuzziWaterJetsIntakeCount: (data as any).jacuzzi_water_jets_intake_count ?? undefined,
    jacuzziWaterPumpQty: (data as any).jacuzzi_water_pump_qty ?? undefined,
    jacuzziWaterPumpArticleId: (data as any).jacuzzi_water_pump_article_id || undefined,
    jacuzziPiezoButtonsCount: (data as any).jacuzzi_piezo_buttons_count ?? undefined,
    jacuzziFiltrationPumpArticleId: (data as any).jacuzzi_filtration_pump_article_id || undefined,
    jacuzziFiltrationPumpQty: (data as any).jacuzzi_filtration_pump_qty ?? undefined,
    jacuzziFilterArticleId: (data as any).jacuzzi_filter_article_id || undefined,
    jacuzziFilterQty: (data as any).jacuzzi_filter_qty ?? undefined,
    jacuzziLedArticleId: (data as any).jacuzzi_led_article_id || undefined,
    jacuzziLedCount: (data as any).jacuzzi_led_count ?? undefined,
    jacuzziHeatPumpArticleId: (data as any).jacuzzi_heat_pump_article_id || undefined,
    jacuzziHeatPumpQty: (data as any).jacuzzi_heat_pump_qty ?? undefined,
    jacuzziSalineElectrolysisArticleId: (data as any).jacuzzi_saline_electrolysis_article_id || undefined,
    jacuzziSalineElectrolysisQty: (data as any).jacuzzi_saline_electrolysis_qty ?? undefined,
    constructionSystem: data.construction_system as any,
    waterproofingSystem: data.waterproofing_system as any,
    paymentConditions: data.payment_conditions, observations: data.observations,
    comercialId: data.comercial_id,
    contractantName: data.contractant_name || undefined,
    contractantNif: data.contractant_nif || undefined,
    contractantAddress: data.contractant_address || undefined,
    contractantTown: data.contractant_town || undefined,
    obraLocation: data.obra_location || undefined,
    coronamentActuacio: data.coronament_actuacio || undefined,
    coronamentTipus: data.coronament_tipus || undefined,
    coronamentFormat: data.coronament_format || undefined,
    coronamentMl: Number(data.coronament_ml) || undefined,
    coronamentEncofratMl: Number(data.coronament_encofrat_ml) || undefined,
    coronamentModelId: data.coronament_model_id || undefined,
    coronamentModelADeterminar: data.coronament_model_a_determinar ?? undefined,
    coronamentBeurada: data.coronament_beurada || undefined,
    coronamentBeuradaColor: data.coronament_beurada_color || undefined,
    coronamentObservacions: data.coronament_observacions || undefined,
    coronamentPeces: data.coronament_peces || undefined,
    coronamentInclos: (data as any).coronament_inclos ?? true,
    revestimentActuacio: data.revestiment_actuacio || undefined,
    revestimentTipus: data.revestiment_tipus || undefined,
    revestimentFormat: data.revestiment_format || undefined,
    revestimentQualitat: data.revestiment_qualitat || undefined,
    revestimentModelId: data.revestiment_model_id || undefined,
    revestimentModelADeterminar: data.revestiment_model_a_determinar ?? undefined,
    revestimentBeurada: data.revestiment_beurada || undefined,
    revestimentBeuradaColor: data.revestiment_beurada_color || undefined,
    revestimentPecesEspecials: data.revestiment_peces_especials ?? undefined,
    revestimentMigCanya: data.revestiment_mig_canya ?? undefined,
    revestimentInclos: (data as any).revestiment_inclos ?? true,
    opcionalRevestimentTipus: data.opcional_revestiment_tipus || undefined,
    opcionalRevestimentFormat: data.opcional_revestiment_format || undefined,
    opcionalRevestimentModelId: data.opcional_revestiment_model_id || undefined,
    opcionalRevestimentBeurada: data.opcional_revestiment_beurada || undefined,
    opcionalRevestimentBeuradaColor: data.opcional_revestiment_beurada_color || undefined,
    revestimentExteriorInclos: (data as any).revestiment_exterior_inclos ?? false,
    revestimentExteriorFormat: (data as any).revestiment_exterior_format || undefined,
    revestimentExteriorModelId: (data as any).revestiment_exterior_model_id || undefined,
    revestimentExteriorModelADeterminar: (data as any).revestiment_exterior_model_a_determinar ?? undefined,
    revestimentExteriorBeurada: (data as any).revestiment_exterior_beurada || undefined,
    revestimentExteriorBeuradaColor: (data as any).revestiment_exterior_beurada_color || undefined,
    instalFiltrePoliesId: data.instal_filtre_polies_id || undefined,
    instalFiltreEspecialId: data.instal_filtre_especial_id || undefined,
    instalAfmEnabled: data.instal_afm_enabled ?? undefined,
    instalAfmArticleId: data.instal_afm_article_id || undefined,
    instalCanviSorraEnabled: data.instal_canvi_sorra_enabled ?? undefined,
    instalCanviSorraArticleId: data.instal_canvi_sorra_article_id || undefined,
    instalBombaOnoffId: data.instal_bomba_onoff_id || undefined,
    instalBombaVariableId: data.instal_bomba_variable_id || undefined,
    instalWifiEnabled: data.instal_wifi_enabled ?? undefined,
    instalWifiArticleId: data.instal_wifi_article_id || undefined,
    instalPrefiltreEnabled: (data as any).instal_prefiltre_enabled ?? undefined,
    instalPrefiltreArticleId: (data as any).instal_prefiltre_article_id || undefined,
    instalPrefiltreQty: (data as any).instal_prefiltre_qty ?? undefined,
    marginPctAdjustment: (data as any).margin_pct_adjustment != null ? Number((data as any).margin_pct_adjustment) : undefined,
    instalDosificacioStdId: data.instal_dosificacio_std_id || undefined,
    instalHidrolisiId: data.instal_hidrolisi_id || undefined,
    instalQuadreId: data.instal_quadre_id || undefined,
    instalQuadreDisplayText: (data as any).instal_quadre_display_text || undefined,
    instalQuadreBaseCost: (data as any).instal_quadre_base_cost != null ? Number((data as any).instal_quadre_base_cost) : undefined,
    instalQuadreBaseSale: (data as any).instal_quadre_base_sale != null ? Number((data as any).instal_quadre_base_sale) : undefined,
    instalQuadreAddonNfCost: (data as any).instal_quadre_addon_nf_cost != null ? Number((data as any).instal_quadre_addon_nf_cost) : undefined,
    instalQuadreAddonNfSale: (data as any).instal_quadre_addon_nf_sale != null ? Number((data as any).instal_quadre_addon_nf_sale) : undefined,
    instalQuadreAddonBcCost: (data as any).instal_quadre_addon_bc_cost != null ? Number((data as any).instal_quadre_addon_bc_cost) : undefined,
    instalQuadreAddonBcSale: (data as any).instal_quadre_addon_bc_sale != null ? Number((data as any).instal_quadre_addon_bc_sale) : undefined,
    instalQuadreFinalCost: (data as any).instal_quadre_final_cost != null ? Number((data as any).instal_quadre_final_cost) : undefined,
    instalQuadreFinalSale: (data as any).instal_quadre_final_sale != null ? Number((data as any).instal_quadre_final_sale) : undefined,
    instalQuadreManualOverride: (data as any).instal_quadre_manual_override ?? undefined,
    instalQuadreRecommendedId: (data as any).instal_quadre_recommended_id || undefined,
    instalFiltrePoliesQty: data.instal_filtre_polies_qty ?? undefined,
    instalFiltreEspecialQty: data.instal_filtre_especial_qty ?? undefined,
    instalBombaOnoffQty: data.instal_bomba_onoff_qty ?? undefined,
    instalBombaVariableQty: data.instal_bomba_variable_qty ?? undefined,
    instalDosificacioStdQty: data.instal_dosificacio_std_qty ?? undefined,
    instalHidrolisiQty: data.instal_hidrolisi_qty ?? undefined,
    // Budgets saved before the instal_filtre_polies_opcional column existed
    // have it as null/undefined — default to opcional=true (safe): if Especial
    // was the one included, Polies MUST be opcional to respect mutual
    // exclusivity; if there's no clear signal either way, still default to
    // opcional rather than silently introducing a new "inclòs" item into an
    // already-saved/accepted budget.
    instalFiltrePoliesOpcional:
      (data as any).instal_filtre_polies_opcional !== null && (data as any).instal_filtre_polies_opcional !== undefined
        ? (data as any).instal_filtre_polies_opcional
        : true,
    instalFiltreEspecialOpcional: data.instal_filtre_especial_opcional ?? undefined,
    instalBombaOnoffOpcional: data.instal_bomba_onoff_opcional ?? undefined,
    instalBombaVariableOpcional: data.instal_bomba_variable_opcional ?? undefined,
    instalDosificacioStdOpcional: data.instal_dosificacio_std_opcional ?? undefined,
    instalHidrolisiOpcional: data.instal_hidrolisi_opcional ?? undefined,
    instalAfmQty: data.instal_afm_qty ?? undefined,
    instalCanviMediArticleId: data.instal_canvi_medi_article_id || undefined,
    instalCanviMediFiltre: data.instal_canvi_medi_filtre || undefined,
    instalDepuracioEnabled: data.instal_depuracio_enabled ?? undefined,
    instalBombaEnabled: data.instal_bomba_enabled ?? undefined,
    instalDosificacioEnabled: data.instal_dosificacio_enabled ?? undefined,
    instalQuadreEnabled: data.instal_quadre_enabled ?? undefined,
    guniteMangueraMetres: (data as any).gunite_manguera_metres != null ? Number((data as any).gunite_manguera_metres) : undefined,
    guniteDistanciaKm: (data as any).gunite_distancia_km != null ? Number((data as any).gunite_distancia_km) : undefined,
    instalFontaneriaEnabled: data.instal_fontaneria_enabled ?? undefined,
    instalFontaneriaText: data.instal_fontaneria_text || undefined,
    instalFontaneriaBaseArticleId: data.instal_fontaneria_base_article_id || undefined,
    instalFontaneriaExtraCost: Number(data.instal_fontaneria_extra_cost) || undefined,
    instalFontaneriaTotal: Number(data.instal_fontaneria_total) || undefined,
    instalFontaneriaDistancia: Number(data.instal_fontaneria_distancia) ?? undefined,
    instalFontaneriaLocalTecnic: data.instal_fontaneria_local_tecnic || undefined,
    instalFontaneriaCasetaTipus: (data as any).instal_fontaneria_caseta_tipus || undefined,
    instalFontaneriaPerforacions: data.instal_fontaneria_perforacions ?? undefined,
    instalFontaneriaPerforacionsArticleId: data.instal_fontaneria_perforacions_article_id || undefined,
    instalFontaneriaRasas: data.instal_fontaneria_rasas || undefined,
    instalElectricaEnabled: data.instal_electrica_enabled ?? undefined,
    instalElectricaText: data.instal_electrica_text || undefined,
    instalElectricaBaseArticleId: data.instal_electrica_base_article_id || undefined,
    instalElectricaExtraCost: Number(data.instal_electrica_extra_cost) || undefined,
    instalElectricaTotal: Number(data.instal_electrica_total) || undefined,
    instalElectricaDistancia: Number(data.instal_electrica_distancia) ?? undefined,
    instalCasetaUbicacio: data.instal_caseta_ubicacio || undefined,
    instalCasetaObservacions: data.instal_caseta_observacions || undefined,
    instalCasetaEnabled: data.instal_caseta_enabled ?? undefined,
    instalCasetaObraLlarg: (data as any).instal_caseta_obra_llarg ?? undefined,
    instalCasetaObraAmple: (data as any).instal_caseta_obra_ample ?? undefined,
    instalCasetaObraAlt: (data as any).instal_caseta_obra_alt ?? undefined,
    instalCasetaObraPortes: (data as any).instal_caseta_obra_portes || undefined,
    accImpulsorsQty: data.acc_impulsors_qty ?? undefined,
    accImpulsorsModelId: data.acc_impulsors_model_id || undefined,
    accBasicsColor: ((data as any).acc_basics_color as 'blanc' | 'color') || undefined,
    accSkimmersQty: data.acc_skimmers_qty ?? undefined,
    accSkimmersModelId: data.acc_skimmers_model_id || undefined,
    accEmbornalQty: data.acc_embornal_qty ?? undefined,
    accEmbornalModelId: data.acc_embornal_model_id || undefined,
    accFocusLedQty: data.acc_focus_led_qty ?? undefined,
    accFocusLedModelId: data.acc_focus_led_model_id || undefined,
    accFocusLedVariant: data.acc_focus_led_variant || undefined,
    accFocusLedText: data.acc_focus_led_text || undefined,
    accReguladorQty: data.acc_regulador_qty ?? undefined,
    accReguladorModelId: data.acc_regulador_model_id || undefined,
    accNetejafonsQty: data.acc_netejafons_qty ?? undefined,
    accNetejafonsModelId: data.acc_netejafons_model_id || undefined,
    accProjectorMiniLedQty: data.acc_projector_mini_led_qty ?? undefined,
    accProjectorMiniLedModelId: data.acc_projector_mini_led_model_id || undefined,
    accControlRgbQty: data.acc_control_rgb_qty ?? undefined,
    accControlRgbModelId: data.acc_control_rgb_model_id || undefined,
    accEscalaEnabled: data.acc_escala_enabled ?? undefined,
    accEscalaQty: data.acc_escala_qty ?? undefined,
    accEscalaModelId: data.acc_escala_model_id || undefined,
    accDutxaEnabled: data.acc_dutxa_enabled ?? undefined,
    accDutxaQty: data.acc_dutxa_qty ?? undefined,
    accDutxaModelId: data.acc_dutxa_model_id || undefined,
    accPlatDutxaEnabled: data.acc_plat_dutxa_enabled ?? undefined,
    accPlatDutxaQty: data.acc_plat_dutxa_qty ?? undefined,
    accCascadaEnabled: data.acc_cascada_enabled ?? undefined,
    accCascadaQty: data.acc_cascada_qty ?? undefined,
    accCascadaModelId: data.acc_cascada_model_id || undefined,
    accSalvavidesEnabled: data.acc_salvavides_enabled ?? undefined,
    accSalvavidesQty: data.acc_salvavides_qty ?? undefined,
    accSalvavidesModelId: data.acc_salvavides_model_id || undefined,
    accBaranaEnabled: data.acc_barana_enabled ?? undefined,
    accBaranaQty: data.acc_barana_qty ?? undefined,
    accBaranaModelId: data.acc_barana_model_id || undefined,
    annexNotes: data.annex_notes || undefined,
    annexProjecteEstat: data.annex_projecte_estat || undefined,
    annexProjecteArticleId: data.annex_projecte_article_id || undefined,
    annexProjecteQty: data.annex_projecte_qty ?? undefined,
    annexExcavacioEstat: data.annex_excavacio_estat || undefined,
    annexExcavacioImport: Number(data.annex_excavacio_import) || undefined,
    annexExcavacioReompliment: Number(data.annex_excavacio_reompliment) || undefined,
    annexExcavacioPill1Title: (data as any).annex_excavacio_pill1_title || undefined,
    annexExcavacioPill2Title: (data as any).annex_excavacio_pill2_title || undefined,
    annexExcavacioText1: (data as any).annex_excavacio_text1 || undefined,
    annexExcavacioText2: (data as any).annex_excavacio_text2 || undefined,
    annexExcavacioManoObraOverride:
      (data as any).annex_excavacio_mano_obra_override != null
        ? Number((data as any).annex_excavacio_mano_obra_override)
        : undefined,
    annexExcavacioReomplimentOverride:
      (data as any).annex_excavacio_reompliment_override != null
        ? Number((data as any).annex_excavacio_reompliment_override)
        : undefined,
    annexPavimentEstat: data.annex_paviment_estat || undefined,
    annexPavimentTipus: data.annex_paviment_tipus || undefined,
    annexPavimentReformaEnabled: (data as any).annex_paviment_reforma_enabled ?? undefined,
    annexPavimentNouEnabled: (data as any).annex_paviment_nou_enabled ?? undefined,
    annexPavimentRetiradaEnabled: data.annex_paviment_retirada_enabled ?? undefined,
    annexPavimentRetiradaM2: Number(data.annex_paviment_retirada_m2) || undefined,
    annexPavimentRegularitzacioEnabled: data.annex_paviment_regularitzacio_enabled ?? undefined,
    annexPavimentRegularitzacioM2: Number(data.annex_paviment_regularitzacio_m2) || undefined,
    annexPavimentActuacio: data.annex_paviment_actuacio || undefined,
    annexPavimentFormigoEnabled: data.annex_paviment_formigo_enabled ?? undefined,
    annexPavimentFormigoM2: Number(data.annex_paviment_formigo_m2) || undefined,
    annexPavimentMaterial: data.annex_paviment_material || undefined,
    annexPavimentFormat: data.annex_paviment_format || undefined,
    annexPavimentM2: Number(data.annex_paviment_m2) || undefined,
    annexPavimentModelId: data.annex_paviment_model_id || undefined,
    annexPavimentModelADeterminar:
      (data as any).annex_paviment_model_a_determinar ?? !data.annex_paviment_model_id,
    annexGespaEstat: data.annex_gespa_estat || undefined,
    annexGespaPreparacioEnabled: data.annex_gespa_preparacio_enabled ?? undefined,
    annexGespaPreparacioM2: Number(data.annex_gespa_preparacio_m2) || undefined,
    annexGespaModel: data.annex_gespa_model || undefined,
    annexGespaM2: Number(data.annex_gespa_m2) || undefined,
    annexGespaArticleId: data.annex_gespa_article_id || undefined,
    annexCobertorEstat: data.annex_cobertor_estat || undefined,
    annexCobertorTipus: ((data as any).annex_cobertor_tipus as any) || undefined,
    annexCobertorModelId: (data as any).annex_cobertor_model_id || undefined,
    annexCobertorLames: ((data as any).annex_cobertor_lames as any) || undefined,
    annexCobertorColorId: (data as any).annex_cobertor_color_id || undefined,
    annexCobertorModelName: cobertorModelName,
    annexCobertorColorName: cobertorColorName,
    annexCobertorManualOverride: (data as any).annex_cobertor_manual_override ?? false,
    annexCobertorManualAmount: (data as any).annex_cobertor_manual_amount ?? undefined,
    annexCobertorCalcCost: (data as any).annex_cobertor_calc_cost ?? undefined,
    annexCobertorCalcSale: (data as any).annex_cobertor_calc_sale ?? undefined,
    annexCobertorCalcBreakdown: (data as any).annex_cobertor_calc_breakdown ?? undefined,
    annexCobertorMurNou: (data as any).annex_cobertor_mur_nou ?? undefined,
    annexCobertorMurM2: (data as any).annex_cobertor_mur_m2 ?? undefined,
    annexCobertorModelCode: (data as any).annex_cobertor_model_code ?? undefined,
    annexRobotEstat: data.annex_robot_estat || undefined,
    annexRobotArticleId: data.annex_robot_article_id || undefined,
    annexRobotQty: data.annex_robot_qty ?? undefined,
    annexBombaCalorEstat: data.annex_bomba_calor_estat || undefined,
    annexBombaCalorCoberta: data.annex_bomba_calor_coberta ?? undefined,
    annexBombaCalorDesde: data.annex_bomba_calor_des_de || undefined,
    annexBombaCalorFinsA: data.annex_bomba_calor_fins_a || undefined,
    annexBombaCalorTemperatura: data.annex_bomba_calor_temperatura ?? undefined,
    annexBombaCalorArticleId: data.annex_bomba_calor_article_id || undefined,
    annexBombaCalorKwRequired: (data as any).annex_bomba_calor_kw_required ?? undefined,
    annexNetejafonsEstat: data.annex_netejafons_estat || undefined,
    annexNetejafonsFons: data.annex_netejafons_fons ?? undefined,
    annexNetejafonsEscala: data.annex_netejafons_escala ?? undefined,
    annexNetejafonsPlataforma: data.annex_netejafons_plataforma ?? undefined,
    annexNetejafonsTotal: data.annex_netejafons_total ?? undefined,
    annexNetejafonsExtraCost: Number(data.annex_netejafons_extra_cost) || undefined,
    annexNetejafonsArticleId: data.annex_netejafons_article_id || undefined,
    autoportantModel: ((data as any).autoportant_model as any) || undefined,
    autoportantAmple: (data as any).autoportant_ample || undefined,
    autoportantLlarg: (data as any).autoportant_llarg || undefined,
    autoportantAlturaAigua: (data as any).autoportant_altura_aigua || undefined,
    autoportantCoronaKey: (data as any).autoportant_corona_key || undefined,
    autoportantRevestimentKey: (data as any).autoportant_revestiment_key || undefined,
    autoportantRevestimentExteriorKey: (data as any).autoportant_revestiment_exterior_key || undefined,
    autoportantMorterColor: ((data as any).autoportant_morter_color as any) || undefined,
    autoportantOpcAsientoAcrilicoQty: (data as any).autoportant_opc_asiento_acrilico_qty != null ? Number((data as any).autoportant_opc_asiento_acrilico_qty) : undefined,
    autoportantOpcColchoneta: (data as any).autoportant_opc_colchoneta ?? undefined,
    autoportantOpcCubiertaElectrica: (data as any).autoportant_opc_cubierta_electrica ?? undefined,
    autoportantOpcBancoGresiteQty: (data as any).autoportant_opc_banco_gresite_qty != null ? Number((data as any).autoportant_opc_banco_gresite_qty) : undefined,
    autoportantOpcSpa: (data as any).autoportant_opc_spa ?? undefined,
    autoportantOpcCascada: (data as any).autoportant_opc_cascada ?? undefined,
    autoportantOpcAsientoPorcelanicoQty: (data as any).autoportant_opc_asiento_porcelanico_qty != null ? Number((data as any).autoportant_opc_asiento_porcelanico_qty) : undefined,
    autoportantOpcCristal: (data as any).autoportant_opc_cristal ?? undefined,
    autoportantTransportKm: (data as any).autoportant_transport_km != null ? Number((data as any).autoportant_transport_km) : undefined,
    autoportantTransportKmOverride: (data as any).autoportant_transport_km_override ?? undefined,
    autoportantTransportCost: (data as any).autoportant_transport_cost != null ? Number((data as any).autoportant_transport_cost) : undefined,
    autoportantTransportSale: (data as any).autoportant_transport_sale != null ? Number((data as any).autoportant_transport_sale) : undefined,
    autoportantTransportUserEdited: (data as any).autoportant_transport_user_edited ?? undefined,
    phases,
    currentCoating: data.current_coating || undefined,
    constructionYear: data.construction_year ?? undefined,
    generalCondition: data.general_condition || undefined,
    detectedProblems: (data.detected_problems as string[]) || undefined,
    rehabWorks: (data.rehab_works as string[]) || undefined,
    rehabNotes: (data.rehab_notes as Record<string, string>) || undefined,
    newCoating: data.new_coating || undefined,
    filtrationSystem: data.filtration_system || undefined,
    hasRobot: data.has_robot ?? undefined,
    hasCover: data.has_cover ?? undefined,
    maintenanceServices: (data.maintenance_services as string[]) || undefined,
    maintenancePeriodicity: data.maintenance_periodicity || undefined,
    maintenancePrice: data.maintenance_price ?? undefined,
    maintenancePlan: ((data as any).maintenance_plan as any) || undefined,
    photoUrl: data.photo_url || undefined,
  } as BudgetDraft;

  return { draft, raw: data };
}