
UPDATE public.formula_variables SET label = 'Largo de la piscina (m)' WHERE variable_name = 'pool_length';
UPDATE public.formula_variables SET label = 'Ancho de la piscina (m)' WHERE variable_name = 'pool_width';
UPDATE public.formula_variables SET label = 'Profundidad mínima (m)' WHERE variable_name = 'pool_depth_min';
UPDATE public.formula_variables SET label = 'Profundidad máxima (m)' WHERE variable_name = 'pool_depth_max';
UPDATE public.formula_variables SET label = 'Profundidad media (m)' WHERE variable_name = 'pool_depth_avg';
UPDATE public.formula_variables SET label = 'Superficie del vaso (m²)' WHERE variable_name = 'pool_surface';
UPDATE public.formula_variables SET label = 'Perímetro de la piscina (ml)' WHERE variable_name = 'pool_perimeter';
UPDATE public.formula_variables SET label = 'Volumen en litros' WHERE variable_name = 'pool_volume_liters';
UPDATE public.formula_variables SET label = 'Superficie total (vaso + escalera exterior)' WHERE variable_name = 'total_surface';
UPDATE public.formula_variables SET label = 'Metros lineales de coronamiento' WHERE variable_name = 'coronament_ml';
UPDATE public.formula_variables SET label = 'Sistema de impermeabilización' WHERE variable_name = 'waterproofing_system';
UPDATE public.formula_variables SET label = 'Tipo de escalera interior' WHERE variable_name = 'interior_stair_type';
UPDATE public.formula_variables SET label = 'Ancho de la escalera (m)' WHERE variable_name = 'stairs_width';
UPDATE public.formula_variables SET label = 'Largo de la escalera (m)' WHERE variable_name = 'stairs_length';
UPDATE public.formula_variables SET label = 'Altura escalones (m)' WHERE variable_name = 'stairs_height';
UPDATE public.formula_variables SET label = 'Largo de la plataforma (m)' WHERE variable_name = 'platform_length';
UPDATE public.formula_variables SET label = 'Ancho de la plataforma (m)' WHERE variable_name = 'platform_width';
UPDATE public.formula_variables SET label = 'Largo escalera exterior (m)' WHERE variable_name = 'ext_stair_length';
UPDATE public.formula_variables SET label = 'Ancho escalera exterior (m)' WHERE variable_name = 'ext_stair_width';
UPDATE public.formula_variables SET label = 'Tiene escalera exterior' WHERE variable_name = 'has_exterior_stair';
UPDATE public.formula_variables SET label = 'Sistema constructivo (gunite/bloque)' WHERE variable_name = 'construction_system';
UPDATE public.formula_variables SET label = 'Tipo de coronamiento' WHERE variable_name = 'coronament_tipus';
UPDATE public.formula_variables SET label = 'Formato de coronamiento' WHERE variable_name = 'coronament_format';
UPDATE public.formula_variables SET label = 'Actuación de coronamiento' WHERE variable_name = 'coronament_actuacio';
UPDATE public.formula_variables SET label = 'Tipo de revestimiento' WHERE variable_name = 'revestiment_tipus';
UPDATE public.formula_variables SET label = 'Formato de revestimiento' WHERE variable_name = 'revestiment_format';
UPDATE public.formula_variables SET label = 'Actuación de revestimiento' WHERE variable_name = 'revestiment_actuacio';
UPDATE public.formula_variables SET label = 'Cantidad de impulsores' WHERE variable_name = 'acc_impulsors_qty';
UPDATE public.formula_variables SET label = 'Cantidad de skimmers' WHERE variable_name = 'acc_skimmers_qty';
UPDATE public.formula_variables SET label = 'Cantidad de sumideros' WHERE variable_name = 'acc_embornal_qty';
UPDATE public.formula_variables SET label = 'Cantidad de focos LED' WHERE variable_name = 'acc_focus_led_qty';
UPDATE public.formula_variables SET label = 'Cantidad de reguladores de nivel' WHERE variable_name = 'acc_regulador_qty';
UPDATE public.formula_variables SET label = 'Cantidad de limpiafondos' WHERE variable_name = 'acc_netejafons_qty';
UPDATE public.formula_variables SET label = 'Cantidad proyectores mini LED' WHERE variable_name = 'acc_projector_mini_led_qty';
UPDATE public.formula_variables SET label = 'Cantidad control RGB' WHERE variable_name = 'acc_control_rgb_qty';
UPDATE public.formula_variables SET label = 'Altura de la plataforma (m)' WHERE variable_name = 'platform_height';
UPDATE public.formula_variables SET label = 'Largo del banco (m)' WHERE variable_name = 'bench_length';
UPDATE public.formula_variables SET label = 'Ancho del banco (m)' WHERE variable_name = 'bench_width';
UPDATE public.formula_variables SET label = 'Altura del banco (m)' WHERE variable_name = 'bench_height';
UPDATE public.formula_variables SET label = 'Superficie escalera exterior (m²)' WHERE variable_name = 'ext_stair_surface';
