ALTER TABLE public.budgets
  ADD COLUMN IF NOT EXISTS has_electrolisi BOOLEAN DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS kit_manguera_size TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS kit_pertiga_size TEXT DEFAULT NULL;