
ALTER TABLE public.budgets
  ADD COLUMN IF NOT EXISTS pool_disposition TEXT NOT NULL DEFAULT 'enterrada',
  ADD COLUMN IF NOT EXISTS altura_vista NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS has_access_stair BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS access_stair_width NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS access_stair_length NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS access_stair_height NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS access_platform_width NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS access_platform_length NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS access_platform_height NUMERIC NOT NULL DEFAULT 0;
